		var tl_helper_l10n = {
			'focus_on_field': 'Coloque o cursor em um dos campos do formulário',
			'form_filled_ok': 'Aparentemente todos os campos obrigatórios estão preenchidos corretamente. Basta seguir adiante.',
			'form_filled_fail': 'Um ou mais campos obrigatórios ainda estão vazios ou preenchidos de forma incorreta.'
		};
		
		var tl_helper_topics = {
			'timeline': {
				parentSelector: '#col-left',
				bindCloseSelector: '#importbtn',
				title: 'Ajudante: Criar uma nova timeline',
				subtitle: '',
				content: 'Uma timeline é composta por uma ou mais faixas, sendo uma a principal onde estão os eventos com seus títulos e textos. As faixas adicionais são usadas para o visitante ter uma visão geral sobre a timeline ou simplesmente poder navegar por ela mais facilmente.',
				fields: [
					{ id: 'tl_name',
						name: 'Dê um nome para a sua timeline',
						description: 'Esse nome será usado para gerar o ID da timeline (minúsculas, sem acentos ou espaços. Por ex., &quot;A b &ccedil;&quot; - &quot;a_b_c&quot;).',
						required: true },
					{ id: 'tl_date',
						name: 'Data para centralizar a timeline',
						description: 'Se definida, forçará a timeline a iniciar com essa data no centro.<br />Se usar a palavra especial &quot;now&quot; em lugar de uma data, o centro da timeline será a data atual. Em outras palavras, a timeline irá andar com o passar dos dias.',
						required: false },
					{ id: 'tl_timezone',
						name: 'Fuso horário',
						description: 'Informe o fuso horário para a sua localização (por ex. 2 ou -3).',
						re: /^\-?\d$/,
						required: true },
					{ id: 'tl_orientation',
						name: 'Orientação da Timeline',
						description: 'A timeline pode ter orientação vertical ou horizontal (padrão: horizontal).',
						required: true },
					{ id: 'tl_width',
						name: 'Largura da timeline',
						description: 'Largura para a timeline. Se estiver vazio, assumirá 100%.',
						required: false },
					{ id: 'tl_height',
						name: 'Altura da timeline',
						description: 'A altura padrão é de 300 pixels. Para modificar, defina esse parâmetro.',
						required: false },
					{ id: 'tl_bubble_width',
						name: 'Largura do balão',
						description: 'Largura para o balão que abre quando um evento é clicado.',
						required: false },
					{ id: 'tl_bubble_height',
						name: 'Altura do balão',
						description: 'Altura para o balão que abre quando um evento é clicado.',
						required: false }
				]
			},
			'band': {
				parentSelector: '#addband',
				bindCloseSelector: '#closeaddband',
				title: 'Ajudante: Adicionando uma nova faixa',
				subtitle: '',
				content: 'As faixas podem ter unidades de tempo e temas diferentes entre si. Atenção com a definição das larguras das faixas, pois a soma de todas as larguras deve ser exatamente 100%.',
				fields: [
					{ id: 'tl_band_width',
						name: 'Largura da banda',
						description: 'Esta é a largura da faixa em relação às outras faixas, não a largura do elemento. Numa timeline horizontal (como é o padrão), essa largura será vista verticalmente.',
						required: true },
					{ id: 'tl_band_intervalUnit',
						name: 'Unidade de tempo',
						description: 'A unidade de tempo para essa faixa',
						required: true },
					{ id: 'tl_band_timeZone',
						name: 'Fuso horário',
						description: 'Esse valor deveria seguir o valor definido para a timeline.',
						re: /^\-?\d$/,
						required: true },
					{ id: 'tl_band_intervalPixels',
						name: 'Tamanho do intervalo',
						description: 'Aqui definimos a distância entre os marcadores, dentro da unidade especificada.',
						re: /^\d+$/,
						required: true },
					{ id: 'tl_band_trackHeight',
						name: 'Altura da linha',
						description: 'Os eventos são disposts na timeline em &quot;linhas imaginárias&quot; que formam o padrão visual. Aqui podemos definir a altura dessas linhas (na unidade CSS &quot;em&quot;).',
						required: false },
					{ id: 'tl_band_trackGap',
						name: 'Espaçamento entre as linhas',
						description: 'Defina aqui o espaçamento entre as &quot;linhas imaginárias&quot; que formam o padrão visual.',
						required: false },
					{ id: 'tl_band_showEventText',
						name: 'Mostrar títulos nos eventos',
						description: 'Se essa faixa é apenas um overview da timeline, talvez seja melhor não mostrar os títulos nos eventos.',
						required: false },
					{ id: 'tl_band_layout',
						name: 'Tema',
						description: 'Há três diferentes modos de exibir uma faixa: &quot;original&quot;, &quot;overview&quot; (visão geral) e &quot;detailed&quot; (detalhado)',
						required: true }
				]
			},
			'decorator': {
				parentSelector: '#adddec',
				bindCloseSelector: '#closeadddec',
				title: 'Ajudante: Adicionar um decorador',
				subtitle: '',
				content: 'Os decoradores são um modo de realçar determinado período de tempo na timeline. Para nós, os decoradores são iguais para todas as faixas.',
				readyCallback: function() {
					var typ = jQuery('#tl_dec_type').val(), not = typ == 'track' ? '#tl_dec_width' : '#tl_dec_endTime,#tl_dec_startLabel,#tl_dec_endLabel,#tl_dec_inFront';
					return (jQuery('.required').not(not).length == jQuery('.field-ready').not(not).length);
				},
				fields: [
					{ id: 'tl_dec_type',
						name: 'Tipo de decorador',
						description: 'Há dois tipos disponíveis. Para realçar um período de tempo, use &quot;faixa&quot;, se o interesse é ressaltar uma data apenas, use &quot;ponto&quot;.',
						required: true },
					{ id: 'tl_dec_unit',
						name: 'Unidade de tempo',
						description: 'Um decorador pode ter uma unidade de tempo diferente daquela atribuída à banda onde será inserido.',
						required: true },
					{ id: 'tl_dec_startTime',
						name: 'Data inicial',
						description: 'Data do evento para tipo &quot;ponto&quot; ou data de início do período para &quot;faixa&quot;.',
						required: true },
					{ id: 'tl_dec_endTime',
						name: 'Data final',
						description: 'Data do final do período (apenas para &quot;faixa&quot;).',
						required: true },
					{ id: 'tl_dec_startLabel',
						name: 'Texto inicial',
						description: 'Se não estiver vazio, essa valor será impresso imediatamente antes do início da faixa.',
						required: false },
					{ id: 'tl_dec_endLabel',
						name: 'Texto final',
						description: 'Se não estiver vazio, essa valor será impresso logo após o final da faixa.',
						required: false },
					{ id: 'tl_dec_width',
						name: 'Largura',
						description: 'O decorador de tipo &quot;ponto&quot; é exibido como uma linha que cruza a timeline perpendicularmente. Defina aqui a largura dessa linha.',
						required: true },
					{ id: 'tl_dec_color',
						name: 'Cor do decorador',
						description: 'Defina uma cor de fundo personalizada.',
						required: false },
					{ id: 'tl_dec_cssClass',
						name: 'Classe CSS',
						description: 'Se deseja um nível mais alto de personalização, você pode definir uma classe CSS para formatar seu decorador manualmente.',
						required: false },
					{ id: 'tl_dec_opacity',
						name: 'Opacidade',
						description: 'Pode-se definir uma opacidade para o decorador (um valor entre 0 e 1).',
						required: false },
					{ id: 'tl_dec_inFront',
						name: 'Posicionar na frente',
						description: 'Marcando Sim, esse decorador será colocado o mais alto possível na pilha de camadas que form a timeline.',
						required: false }
				]
			},
			'event': {
				parentSelector: '#col-left',
				title: 'Ajudante: Adicionar um evento',
				subtitle: '',
				content: 'Há dois tipos de evento que geram formatações diferentes. Um aponta para um único momento no tempo e é exibido como uma bolinha com o texto ao lado, o segundo mostra um período e é exibido como uma linha com o texto abaixo. A forma de diferenciar é a Data final -  se estiver vazia é uma data, senão é um período.',
				fields: [
					{ id: 'tl_event_title',
						name: 'Título do evento',
						description: 'Texto visível para este evento na timeline.',
						required: true },
					{ id: 'tl_event_start',
						name: 'Data inicial',
						description: 'Data do evento (ou data de início do período).',
						required: true },
					{ id: 'tl_event_end',
						name: 'Data final',
						description: 'Data de término do período.',
						required: false },
					{ id: 'tl_event_caption',
						name: 'Text alternativo',
						description: 'Se estiver preenchido, esse texto irá aparecer ao parar o ponteiro do mouse sobre o evento.',
						required: false },
					{ id: 'tl_event_link',
						name: 'URL do link',
						description: 'Definindo uma URL aqui, transformamos o título (que aparece no balão) em um link.',
						required: false },
					{ id: 'tl_event_color',
						name: 'Cor da barra',
						description: 'Se o evento tem início e fim definidos, você pode mudar a cor da linha que irá representar o evento na timeline.',
						required: false },
					{ id: 'tl_event_textColor',
						name: 'Cor do texto',
						description: 'Defina aqui a cor do texto visível do evento na timeline.',
						required: false },
					{ id: 'tl_event_icon',
						name: 'Ícone para o evento',
						description: 'Se definido, o evento será exibido na timeline com essa imagem no lugar da bolinha.',
						required: false },
					{ id: 'tl_event_image',
						name: 'Imagem para o evento',
						description: 'Se definida, essa imagem aparecerá no canto superior direito do balão.',
						required: false },
					{ id: 'tl_event_description',
						name: 'Descrição',
						description: 'Essa descrição é o texto que aparece no balão, quando se clica no título do evento.',
						required: false }
				]
			},
			'hotzone': {
				parentSelector: '#edit_hz_fs',
				title: 'Ajudante: Adicionar Zona em Destaque',
				subtitle: '',
				content: 'As zonas de destaque criam a possibilidade de trabalhar com outras unidades de tempo mescladas com a originalmente escolhida, para esmiuçar mais um determinado período de tempo na timeline.',
				bindCloseSelector: '#edit_hz_fs .cancel',
				fields: [
					{ id: 'tl_hz_startTime',
						name: 'Data de início',
						description: 'Data inicial da zona em destaque na timeline.',
						required: true },
					{ id: 'tl_hz_endTime',
						name: 'Data de término',
						description: 'Data que finaliza a zona em destaque na timeline.',
						required: true },
					{ id: 'tl_hz_unit',
						name: 'Unidade de tempo',
						description: 'Unidade de tempo para essa zona em destaque.',
						required: true },
					{ id: 'tl_hz_magnify',
						name: 'Ampliar',
						description: 'Um número usado como vetor para maximizar os intervalos de tempo na zona em destaque (quanto maior o número, maiores os intervalos).',
						re: /^\-?\d$/,
						required: true },
					{ id: 'tl_hz_multiple',
						name: 'Múltiplo',
						description: 'Um número usado para espaçar as marcações de tempo na timeline. 1 = uma marcação a cada unidade do intervalo escolhido; 2 = marcação a cada duas unidades - e assim por diante.',
						required: false }
				]
			}
		};
